sudo: false
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - pip install tox-travis
# command to run tests
script: tox