# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 09:29:55 2021

@author: edward
"""

import ManuCostModel as man
import os
from ManuCostModel.MapParameters import ReadInputs, ReadInputsXML, ConsistencyCheck

# materials_DB = {'fabric': {'Fabric 1': {'material': 'carbon',
#                                'width': 1000.0,
#                                'length': 100000.0,
#                                'thickness (cured)': 0.1,
#                                'areal weight': 200.0,
#                                'cost': 5.0,
#                                'density of fibres': 1780.0,
#                                'fibre volume fraction': 0.45,
#                                'fibre content': 0.55}},
#                      'resin': {'Resin 1': {'material': 'epoxy',
#                                'hardener name': 'System 3120',
#                                'density': 1100.0,
#                                'resin-hardener ratio': 5.0,
#                                'cost': 3.0,
#                                'cure cycle': 'System3000_cureCycle.csv'}},
#                      'hardener': {'Hardener 1': {'material': 'epoxy curing agent',
#                                'resin name': 'System 3000',
#                                'density': 1100.0,
#                                'resin-hardener ratio': 5.0,
#                                'cost': 10.0}},
#                      'prepreg': {'Prepreg 1': {'material': 'carbon/epoxy',
#                                'fabric name': 'carbon IM',
#                                'resin name': 'epoxy',
#                                'width': 300.0,
#                                'length': 100000.0,
#                                'thickness (cured)': 0.1,
#                                'areal weight': 150.0,
#                                'cost': 100.0,
#                                'density of fibres': 1780.0,
#                                'density of resin': 1100.0,
#                                'fibre volume fraction': 0.55,
#                                'fibre content': 0.60}},
#                      'core': {'Core 1': {'material': 'PMI',
#                                'width': 500.0,
#                                'length': 1000.0,
#                                'thickness': 10.0,
#                                'density': 50.0,
#                                'areal weight': 450.0,
#                                'cost': 5.0}},
#                      'coating': {'Gel Coat 1': {'material': 'epoxy',
#                                'thickness (cured)': 0.2,
#                                'density': 1100.0,
#                                'cost': 3.0}},
#                      'adhesive': {'Adhesive 1': {'material': 'epoxy',
#                                'cost': 30.0,
#                                'cure cycle': 'DP490_cureCycle.csv'}},
#                      'consumables': {'Mould release': {'cost': 30.0,
#                                'areal weight': 1.0,
#                                'scaling variable': 'Surface Area',
#                                'scrap_rate': 0.0},
#                               'Peel ply': {'cost': 30.0,
#                                'areal weight': 200.0,
#                                'scaling variable': 'Surface Area',
#                                'scrap_rate': 0.2},
#                               'Breather fabric': {'cost': 6.0,
#                                'areal weight': 1500.0,
#                                'scaling variable': 'Surface Area',
#                                'scrap_rate': 0.2},
#                               'Flow media': {'cost': 20.0,
#                                'areal weight': 400.0,
#                                'scaling variable': 'Surface Area',
#                                'scrap_rate': 0.2},
#                               'Paint': {'cost': 0.0,
#                                'areal weight': 0.0,
#                                'scaling variable': 'Surface Area',
#                                'scrap_rate': 0.2}}}

# production_methods_DB = {'Method 1': 
#                          {'step 01': {'name': 'Fabric cutting',
#                                      'labourScaling': ['Ply Length', 'fabricCutRate'],
#                                      'labourHours': 0.0,
#                                      'staff': 1.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['Ply cutter'],
#                                      'materials': 'fabric',
#                                      'materialScaling': ['Ply Surface Area', 'areal weight'],
#                                      'scrapRate': 0.25,
#                                      'scrapVar': 'fabric',
#                                      'consumables': ['N/A']},
#                          'step 02': {'name': 'Core cutting',
#                                      'labourScaling': ['Core Ply Length', 'coreCutRate'],
#                                      'labourHours': 0.0,
#                                      'staff': 1.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'core',
#                                      'materialScaling': ['Core Ply Surface Area', 'areal weight'],
#                                      'scrapRate': 0.25,
#                                      'scrapVar': 'core',
#                                      'consumables': ['N/A']},
#                          'step 03': {'name': 'Mould preparation',
#                                      'labourScaling': ['Surface Area', 'mouldPrep'],
#                                      'labourHours': 0.0,
#                                      'staff': 2.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['Lifting equipment', 'mould scenario 2'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['Mould release']},
#                          'step 04': {'name': 'Gel coat application',
#                                      'labourScaling': ['Surface Area', 'gelCoatRate'],
#                                      'labourHours': 0.0,
#                                      'staff': 2.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['Gel coat equipment'],
#                                      'materials': 'coating',
#                                      'materialScaling': ['Surface Area', 'density', 'thickness (cured)'],
#                                      'scrapRate': 0.05,
#                                      'scrapVar': 'coating',
#                                      'consumables': ['N/A']},
#                          'step 05': {'name': 'Fabric layup',
#                                      'labourScaling': ['Ply Surface Area', 'fabricLayup'],
#                                      'labourHours': 0.0,
#                                      'staff': 2.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 06': {'name': 'Core layup',
#                                      'labourScaling': ['Core Ply Surface Area', 'coreLayup'],
#                                      'labourHours': 0.0,
#                                      'staff': 1.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 07': {'name': 'Spar installation',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 1.0,
#                                      'staff': 2.0,
#                                      'activity': 'preform',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 08': {'name': 'Consumables layup',
#                                      'labourScaling': ['Surface Area', 'consLayup'],
#                                      'labourHours': 0.0,
#                                      'staff': 2.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['Vacuum film',
#                                                      'Peel ply',
#                                                      'Flow media',
#                                                      'Release film',
#                                                      'Sealant tape',
#                                                      'VAP membrane',
#                                                      'Resin tube']},
#                          'step 09': {'name': 'Vacuum application',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 0.5,
#                                      'staff': 1.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['Vacuum unit'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 10': {'name': 'Infusion',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 2.0,
#                                      'staff': 1.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'resin',
#                                      'materialScaling': ['Ply Surface Area', 'areal weight'],
#                                      'scrapRate': 0.076,
#                                      'scrapVar': 'resin',
#                                      'consumables': ['N/A']},
#                          'step 11': {'name': 'Cure',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 'material definition',
#                                      'staff': 1.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['Oven'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 12': {'name': 'Remove consumables',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 1.0,
#                                      'staff': 1.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 13': {'name': 'Demould',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 1.0,
#                                      'staff': 2.0,
#                                      'activity': 'cure',
#                                      'capitalEquipment': ['N/A'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']},
#                          'step 14': {'name': 'Surface inspection',
#                                      'labourScaling': 'N/A',
#                                      'labourHours': 5.0,
#                                      'staff': 1.0,
#                                      'activity': 'assembly',
#                                      'capitalEquipment': ['NDT equipment'],
#                                      'materials': 'N/A',
#                                      'scrapRate': 'N/A',
#                                      'scrapVar': 'N/A',
#                                      'consumables': ['N/A']}}}
    
# production_variables_DB = {'Method 1':
#                            {'fabricCutRate': {'name': 'Fabric cut rate',
#                                               'description': 'Cutting rate for fabric materials',
#                                               'value': [0.000555556, 1.0],
#                                               'units': 'hr/m'},
#                           'coreCutRate': {'name': 'Core cut rate',
#                                               'description': 'Cutting rate for core materials',
#                                               'value': [0.000555556, 1.0],
#                                               'units': 'hr/m'},
#                           'mouldPrep': {'name': 'Mould preparation rate',
#                                               'description': 'Rate of mould surface preparation',
#                                               'value': [0.023250047, 1.0],
#                                               'units': 'hr/m^2',
#                                               'reference': 'None'},
#                           'gelCoatRate': {'name': 'Gel coat application rate',
#                                               'description': 'Rate of apply gel coat to the surface of the mould',
#                                               'value': [0.085250171, 1.0],
#                                               'units': 'hr/m^2',
#                                               'reference': 'None'},
#                           'fabricLayup': {'name': 'Fabric layup rate',
#                                               'description': 'Layup rate for dry fabric materials',
#                                               'value': [0.030628891, 0.77006],
#                                               'units': 'hr/m^2',
#                                               'reference': 'None'},
#                           'coreLayup': {'name': 'Core layup rate',
#                                               'description': 'Layup rate for dry core materials',
#                                               'value': [0.007440719, 0.381],
#                                               'units': 'hr/m^2',
#                                               'reference': 'None'},
#                           'consLayup': {'name': 'Consumables layup rate',
#                                               'description': 'Rate of application of consumables on part',
#                                               'value': [0.06975014, 1.0],
#                                               'units': 'hr/m^2',
#                                               'reference': 'None'}},
#                         'General': {'salary': {'name': 'Hourly salary rate',
#                                               'description': 'Average hourly rate of salary for employees',
#                                               'value': 35.0,
#                                               'units': '€/hr',
#                                               'reference': 'None'},
#                          'productHours': {'name': 'Daily production hours',
#                                               'description': 'Number of hours of available production time per day',
#                                               'value': 24.0,
#                                               'units': 'hr/day',
#                                               'reference': 'None'},
#                          'productDays': {'name': 'Number of annual production days',
#                                               'description': 'Number of days available for production time per year',
#                                               'value': 250.0,
#                                               'units': 'days/year',
#                                               'reference': 'None'},
#                          'ppa': {'name': 'Wings per annum',
#                                               'description': 'Number of completed wings produced per annum',
#                                               'value': 100.0,
#                                               'units': 'parts per annum',
#                                               'reference': 'None'}}}

# manufacturing_DB = {'spar': {'fabric': 'Fabric 1',
#                      'resin': 'Resin 1',
#                      'hardener': 'Hardener 1',
#                      'prepreg': 'N/A',
#                      'core': 'N/A',
#                      'adhesive': 'N/A',
#                      'coating': 'N/A',
#                      '# items': 1,
#                      'preforming': 'Method 1',
#                      'preforming_steps_ignore': ['step 02', 'step 04', 'step 06', 'step 08'],
#                      'curing': 'N/A',
#                      'assembly': 'N/A'}}

# inputVars = {'main wing element': 
#                  {'spar1': {'Surface Area': 10.0, 'Ply Surface Area': 500.0, 'Ply Length': 2500.0, 'Part Length': 20.0}, 
#                   'spar2': {'Surface Area': 10.0, 'Ply Surface Area': 500.0, 'Ply Length': 2500.0, 'Part Length': 20.0}, 
#                   'web1': {'Surface Area': 5.0, 'Ply Surface Area': 250.0, 'Ply Length': 450.0, 'Bondline': 40.0, 'Part Length': 20.0, 'Core Surface Area': 50.0, 'Core Ply Length': 100.0, 'Core Ply Surface Area': 100.0}, 
#                   'skin1': {'Surface Area': 40.0, 'Ply Surface Area': 300.0, 'Ply Length': 300.0, 'Bondline': 80.0, 'Part Length': 40.0, 'Core Surface Area': 100.0, 'Core Ply Length': 300.0, 'Core Ply Surface Area': 100.0}, 
#                   'skin2': {'Surface Area': 40.0, 'Ply Surface Area': 300.0, 'Ply Length': 300.0, 'Bondline': 80.0, 'Part Length': 40.0, 'Core Surface Area': 100.0, 'Core Ply Length': 300.0, 'Core Ply Surface Area': 100.0}, 
#                   'wing1': {'Surface Area': 80.0, 'Webs Bondline': 40.0, 'Shells Bondline': 80.0, 'Shell Bondline': 40.0, 'Web Nums': 1.0}}}

directory = os.path.dirname(os.path.realpath(__file__))

structural_inputs = 'ScalingVariables.xml'

inputFileName = "manufacturingDatabase" # Replace with some example file

factory = man.CostModel.Manufacture(directory, inputFileName, processName="Method 1", productName="wing", scaleFile=structural_inputs)

# factory.Scale(True)

# materialDict = factory.MaterialDictionary(manufacturing_DB, 'spar')

# component = man.CostModel.component('spar', 'spar', 'wing', matDetails=materialDict)

# scalingInputs = ReadInputsXML(directory + "\\Input Databases\\" + structural_inputs)

# component.scaleVars = scalingInputs[component.product][component.name+'1']

# component.ProductionDefinition(manufacturing_DB, production_methods_DB)

# component.labour = component.Labour(len(component.productionSteps), activities=factory.activityLevels)

# factory.MaterialsAnalysis(component, materials_DB)

# factory.productionVars = production_variables_DB

def mat_cost_test(component, materials_DB, stepNum):
    return factory.MaterialsCost(component, materials_DB, stepNum)

def mat_test_1(component, materials_DB, stepNum):
    assert mat_cost_test(component, materials_DB, stepNum) == (100.0, 500.0)
    
def mat_test_2(component, materials_DB, stepNum):
    assert mat_cost_test(component, materials_DB, stepNum) == (150.0, 823.5)

def labour_cost_test(component, materials_DB, production_methods_DB, stepNum):
    return factory.LabourCost(component, materials_DB, production_methods_DB, stepNum)


# print(labour_cost_test(component, materials_DB, production_variables_DB, 0))

factory.ProductionAnalysis(scaling=True, readScaling=True)

# factory.TotalCosts()
